#!/bin/bash
#SBATCH --job-name=deep_learning
#SBATCH --time=1-00:00:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive
#SBATCH --partition=staff
#SBATCH --gres=gpu:a30:2
#SBATCH --mem=371G
#SBATCH --output=out
#SBATCH --error=error
module purge
cd /scratch/user/u.ks124812/CSCE636/project/
source modules.sh
source venv/bin/activate
cd training
srun torchrun --nnodes=$nodes --nproc_per_node=2 nn.py