#!/bin/bash
#SBATCH --job-name=deep_learning
#SBATCH --time=1-00:00:00
#SBATCH --ntasks=1
#SBATCH --partition=staff
#SBATCH --cpus-per-task=192
#SBATCH --gres=gpu:a30:2
#SBATCH --mem=371G
#SBATCH --output=out
#SBATCH --error=error

module purge
cd /scratch/user/u.ks124812/CSCE636/project/
source modules.sh
source venv/bin/activate
cd training
torchrun --nproc_per_node=2 --nnodes=1 nn.py
