#!/bin/bash
#SBATCH --job-name=deep_learning
#SBATCH --time=10:00:00
#SBATCH --ntasks=3648
#SBATCH --partition=staff
#SBATCH --cpus-per-task=1
#SBATCH --mem=371G
#SBATCH --output=out
#SBATCH --error=error

module purge
cd /scratch/user/u.ks124812/CSCE636/project/
source modules.sh
make -B main
mpirun a.out
source venv/bin/activate
python3 parser.py
